# Generated by Django 5.0 on 2024-05-27 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda_original', models.CharField(default='CLP', max_length=3)),
                ('total_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda_final', models.CharField(default='CLP', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda_pago', models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], max_length=3)),
                ('metodo_pago', models.CharField(choices=[('ONLINE', 'Online'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='pago.boleta')),
            ],
        ),
    ]
