# Generated by Django 5.0 on 2024-05-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospago',
            name='boleta',
        ),
    ]
