# Generated by Django 5.0 on 2024-05-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_remove_datospago_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospago',
            name='moneda_final',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='datospago',
            name='moneda_original',
            field=models.CharField(default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='datospago',
            name='total_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
