# Generated by Django 5.0 on 2024-05-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_datospago_moneda_final_datospago_moneda_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospago',
            name='total_final',
        ),
    ]
