# Generated by Django 5.0 on 2024-05-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0004_remove_datospago_total_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospago',
            name='moneda_original',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='moneda_final',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='datospago',
            name='moneda_final',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
